GitHubActionsでautopep8フォーマット
progrunner17/honomara_members_site pull request #30
Opened 2020-10-11 04:07 UTC by yurimo36

2020-10-11 14:37 UTC, progrunner17 requested changes
ファイル名もautopep8より一般的な名前にしてくれると良いですー

2020-10-11 14:37 UTC, progrunner17 commented on .github/workflows/autopep8.yml
> +on: pull_request
PRだけでなく、masterへのpushの際もチェックできるようにしてくれると良いですー

2020-10-11 14:37 UTC, progrunner17 commented on .github/workflows/autopep8.yml
> +          git push
フォーマットがコミット履歴に残るのはあんまり良くない気がするから、formatがおかしいときはfailするだけに留めておこう

```suggestion
        run: exit 1
```

2020-10-11 14:37 UTC, progrunner17 commented on .github/workflows/autopep8.yml
> +          args: --exit-code --recursive --in-place --aggressive --aggressive .
```suggestion
          args: --exit-code --recursive --in-place --aggressive .
```
`--aggressive` 二つは少しフォーマットが強すぎるので、1つで

2020-10-11 14:37 UTC, progrunner17 commented on .github/workflows/autopep8.yml
> +name: autopep8
```suggestion
name: "Code Format"
```
Python以外ののフォーマットチェックも追加しやすいように、名前は一般的なものにしておこう

2020-10-11 14:37 UTC, progrunner17 commented on .github/workflows/autopep8.yml
> +          ref: ${{ github.head_ref }}
確証はないけど、多分不要なはず...
```suggestion
```

2020-10-11 14:37 UTC, progrunner17 commented on .github/workflows/autopep8.yml
> +    if: github.event.pull_request.head.repo.full_name == github.repository
pushでも動くようにするためには、無いほうがよさそう

2020-10-11 14:37 UTC, progrunner17 commented on .github/workflows/autopep8.yml
> +  autopep8:
```suggestion
  format_python:
```
単に好みの問題だけど、htmlとかのフォーマットのジョブもいづれは追加することを考えて...

2020-10-11 14:37 UTC, progrunner17 commented on .github/workflows/autopep8.yml
> +      - name: Commit autopep8 changes
```suggestion
      - name: Force fail when the code is not formatted
```

後述の修正に合わせて...

2020-10-11 14:42 UTC, progrunner17 commented
あと、これはしなくてもマージするけど、
PRを修正する際は、`git rebase` を使ってコミット履歴を編集して、同じブランチにforce pushすると取り込みやすいので、助かります。
（rebaseが面倒なら、git rest でヘッドをmasterまで戻してしまってから、再度コミットするほうが楽かも）

今回だと、
* `autopep8 --aggressive` を使うことで生じるpythonコードの変更
* actionsの追加
の2コミットぐらいが丁度良いと思います。

2020-10-11 14:52 UTC, progrunner17 commented
#21

2020-10-11 14:59 UTC, progrunner17 commented
念のため書いておくけど、特に期限もないので、あくまで趣味の範囲内でのんびりやってくれれば大丈夫です〜

2020-10-11 16:22 UTC, yurimo36 commented
修正しました！
現段階でactionsが動かないのは何故でしょう…？

あと、全然無理はしてなくて、研究から逃避してるだけなので大丈夫です笑(ダメ)

2020-10-12 05:09 UTC, progrunner17 requested changes
今のところ僕のリポジトリでテストが走らないのは、単に僕がマージしてないからなので、心配しなくて大丈夫です👍

2020-10-12 05:09 UTC, progrunner17 commented on .github/workflows/code_format.yml
> +      - name: format_python
ここはautopep8で

2020-10-12 05:09 UTC, progrunner17 commented on .github/workflows/code_format.yml
> +  autopep8:
こっちをformat_pythonにしよう

2020-10-12 10:37 UTC, yurimo36 commented
直しました、お願いします🙇‍♀️

2020-10-12 13:15 UTC, merged