色々
progrunner17/honomara_members_site pull request #31
Opened 2020-10-17 09:01 UTC by yurimo36

修正機能の追加は、現時点では使用頻度の高い練習録とアフター録だけです。

2020-10-24 02:46 UTC, progrunner17 requested changes
色々とありがとうー
いくつか修正箇所があるのでよろしくおねがいします。

2020-10-24 02:46 UTC, progrunner17 commented on templates/after_confirm.html
> +              <dd>{{form.date.data.strftime('%Y/%m/%d')}}{{w_list[form.date.data.weekday()]}}</dd>
```suggestion
              <dd>{{form.date.data.strftime('%Y/%m/%d（%a）')}}</dd>
```
とすればw_listはいらないはず

2020-10-24 02:46 UTC, progrunner17 commented on templates/macro.html
> +          {% set w_list = ['(月)', '(火)', '(水)', '(木)', '(金)', '(土)', '(日)'] %}
前のコメント同様、w_listはいらないはず。

2020-10-24 02:46 UTC, progrunner17 commented on templates/macro.html
> +          {{training.date.strftime('%Y/%m/%d')}}{{w_list[training.date.weekday()]}}
前のコメント同様、w_listはいらないはず。

2020-10-24 02:46 UTC, progrunner17 commented on templates/training_confirm.html
> +              <dd>{{form.date.data.strftime('%Y/%m/%d')}}{{w_list[form.date.data.weekday()]}}</dd>
前のコメント同様、w_listはいらないはず。

2020-10-24 02:46 UTC, progrunner17 commented on templates/template.html
> +  });
色々試してみたら、この部分のコードが上手く動かない事があるみたい...
僕もこの辺りの細かい挙動はよくわかってないから、
この部分は放置してマージしようと思うけど、
解決できそうだったらしてくれると助かりますー

2020-10-24 02:46 UTC, progrunner17 commented on templates/after_edit.html
> +      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
jqueryは既に読み込んでいるので、この１行は消してくださいー

2020-10-24 02:46 UTC, progrunner17 commented on templates/after_edit.html
> +      </script>
scriptは個別に切り分けたいので、
edit_template.htmlを参考に、切り出してくださいー

2020-10-24 08:29 UTC, yurimo36 commented on templates/template.html
> +  });
そうなんですね、知らなかったです。
どういう動作をすると動かないんですか？(orブラウザの問題ですか？)

2020-10-24 08:30 UTC, yurimo36 commented
headerのjsはそのままですがそれ以外は直しました🙇‍♀️

2020-10-25 07:39 UTC, progrunner17 commented on templates/template.html
> +  });
firefoxで試したからなのか、ページを再読み込みした時に、うまく動かない事があるみたい...

2020-10-25 07:42 UTC, merged